ALTER TYPE "AccountKind" ADD VALUE 'PLAYER_AVAILABLE';
ALTER TYPE "AccountKind" ADD VALUE 'PLATFORM_TREASURY';
ALTER TYPE "AccountKind" ADD VALUE 'GAME_ESCROW';
ALTER TYPE "AccountKind" ADD VALUE 'TEST_FAUCET';
CREATE TYPE "PlayerStatus" AS ENUM ('ACTIVE','FROZEN','SUSPENDED');
CREATE TYPE "GameSessionStatus" AS ENUM ('CREATED','ACTIVE','COMPLETED','CANCELLED');
CREATE TYPE "WagerStatus" AS ENUM ('PENDING','ACCEPTED','SETTLED','REFUNDED','REJECTED');
CREATE TYPE "SettlementResult" AS ENUM ('LOSS','WIN_SMALL','WIN_LARGE','REFUND');
CREATE TABLE "PlayerProfile" ("userId" UUID PRIMARY KEY REFERENCES "User"("id"), "displayName" TEXT, "status" "PlayerStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX "PlayerProfile_status_createdAt_idx" ON "PlayerProfile"("status","createdAt");
CREATE TABLE "DemoFaucetClaim" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL REFERENCES "User"("id"), "idempotencyKey" TEXT NOT NULL, "amount" BIGINT NOT NULL CHECK ("amount">0), "claimedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE("userId","idempotencyKey"));
CREATE INDEX "DemoFaucetClaim_userId_claimedAt_idx" ON "DemoFaucetClaim"("userId","claimedAt");
CREATE TABLE "Game" ("id" UUID PRIMARY KEY, "slug" TEXT UNIQUE NOT NULL, "name" TEXT NOT NULL, "provider" TEXT NOT NULL, "category" TEXT NOT NULL, "description" TEXT, "thumbnailUrl" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "demoOnly" BOOLEAN NOT NULL DEFAULT true, "minBet" BIGINT NOT NULL CHECK ("minBet">0), "maxBet" BIGINT NOT NULL CHECK ("maxBet">="minBet"), "sortOrder" INTEGER NOT NULL DEFAULT 0, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX "Game_active_sortOrder_id_idx" ON "Game"("active","sortOrder","id");
CREATE TABLE "GameSession" ("id" UUID PRIMARY KEY, "userId" UUID NOT NULL REFERENCES "User"("id"), "gameId" UUID NOT NULL REFERENCES "Game"("id"), "status" "GameSessionStatus" NOT NULL DEFAULT 'ACTIVE', "startedAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "completedAt" TIMESTAMPTZ, "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE INDEX "GameSession_userId_createdAt_id_idx" ON "GameSession"("userId","createdAt","id");
CREATE INDEX "GameSession_gameId_createdAt_idx" ON "GameSession"("gameId","createdAt");
CREATE TABLE "GameWager" ("id" UUID PRIMARY KEY, "sessionId" UUID NOT NULL REFERENCES "GameSession"("id"), "userId" UUID NOT NULL REFERENCES "User"("id"), "gameId" UUID NOT NULL REFERENCES "Game"("id"), "idempotencyKey" TEXT NOT NULL, "settlementKey" TEXT UNIQUE, "stake" BIGINT NOT NULL CHECK ("stake">0), "payout" BIGINT, "status" "WagerStatus" NOT NULL DEFAULT 'PENDING', "result" "SettlementResult", "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now(), "settledAt" TIMESTAMPTZ, "ledgerTransactionId" UUID UNIQUE REFERENCES "LedgerTransaction"("id"), "settlementLedgerTransactionId" UUID UNIQUE REFERENCES "LedgerTransaction"("id"), UNIQUE("userId","idempotencyKey"));
CREATE INDEX "GameWager_sessionId_createdAt_id_idx" ON "GameWager"("sessionId","createdAt","id");
CREATE INDEX "GameWager_userId_createdAt_id_idx" ON "GameWager"("userId","createdAt","id");
